name: build_test
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: View poetry --help
        run: poetry build
      - name: Fake wheel build
        run: |
          mkdir wheelhouse
          touch wheelhouse/fake_wheel.whl
      - uses: actions/upload-artifact@v3
        with:
          path: | 
            wheelhouse/*.whl
            dist/*.tar.gz
      - name: List files
        run: |
          ls -al ./
          ls -al wheelhouse/
          ls -al dist/
  upload:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: wheelhouse
      - name: List files
        run: | 
          ls -al .
          ls -al wheelhouse
          ls -al wheelhouse/artifact
