name: build_test
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.7", "3.8"]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Fake wheel build
        run: |
          mkdir wheelhouse
          touch wheelhouse/fake_wheel{{ $matrix.python-version }}.whl
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/
      - name: List files
        run: |
          ls -al ./
          ls -al wheelhouse/
  tarbuild:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: abatilo/actions-poetry@v2
      - name: Build 
        run: poetry build
      - uses: actions/upload-artifact@v3
        with:
          name: tar
          path: dist/
  upload:
    runs-on: ubuntu-latest
    needs:
      - tarbuild
    steps:
      - uses: actions/download-artifact@v3
      - name: List files
        run: | 
          ls -al .
          ls -al wheels
